### ISSUE TITLE
Nicer URLs

### ISSUE THREAD

**Issue by mkalam-alami** [mkalam-alami/wejam#6]
Replace all `uuid`-based URLs with `name`-based ones. It involves:

* Making sure all entries/events have a name, generated automatically from the title in `entryController.js#saveEntry` (without worrying about name-clashing for now).
* Updating the entry & event controllers routes
* Updating the `controllers/templating.js#buildUrl()` function

Tip: updating the samples in `core/db.js#insertSamples()` to test stuff will be useful.

**Comment by ttencate** [comment]
I started doing this, but realised that there are some problems with slug-based URLs of the form `/event/my-event-name`, `/entry/my-entry-name`:

* Uniqueness is of course a consideration. Fine, [bookshelf-slug](https://github.com/oscaroox/bookshelf-slug) solves this for us by adding sequence numbers, but at the cost of a bunch of database queries.
* If the name changes, should we change the slug? bookshelf-slug does so, breaking any external links. But if we don't change the slug, people are forever stuck with the first name they gave their game.
* Building URLs becomes harder in some situations. Previously you only needed the uuid of the object. Now you need the entire object, or at least its slug field.

I think we can resolve all this by adding _both_ ids _and_ slugs to the url: `/event/3746/my-event-name`, `/entry/36492/my-entry-name`. The controller looks up the object by id, and if the slug doesn't match, it redirects. This is how StackOverflow does it, and I've seen it on many news sites as well. Advantages:

* Uniqueness is guaranteed because we still use ids.
* We can update the slug without breaking external links.
* Building URLs if you don't have the slug at hand is still possible, just leave the slug out. Such a URL will incur a redirect, but this should be the minority case.

The drawback, of course, is that we would still have huge uuids in the URL. So I'm wondering... why do we use uuids in the first place, instead of the customary sequential integers generated by the database?

**Comment by mkalam-alami** [comment]
> I'm wondering... why do we use uuids in the first place [...]

The intended use was for dealing with polymorphic joins (e.g. the target of a user right: `user_role.node_uuid`): UUIDs were a cheap way to prevent ID clashes in such cases. I've since discovered that Bookshelf manages morph relations pretty well natively, with two fields id + target table, which is even better (my original approach only let us do one-way joins).

Other than that I don't think there was any particular use so yes, we can switch back to incrementing integers :) That sounds like an annoying refactoring though, so I suggest you keep the huge uuids for now, we can focus on switching to integers in a separate issue.

Regarding URL formats, the StackOverflow solution sounds good to me. As an exception I think it's safe to consider events won't be renamed often (a big like Github repos), so I wouldn't mind keeping the `/event/we-jam-42` format, that lets people type URLs manually if they want.

About the entries, what would you think of putting them under the event, like: `/event/we-jam-42/entry/123/my-awesome-game`? On one hand it would be more restful... But on the other one it kinda looks ugly and annoying to type by hand...

**Comment by mkalam-alami** [comment]
Wé could be even bolder and remove the `/event` part actually. With either reserved words or just a requirement to have at least one hypen in the event slug

**Comment by ttencate** [comment]
With these fundamental things, my experience is to do them sooner rather than later: the less stuff is built on top of them, the better. So I'll do that first. If nothing else, it will make me more familiar with nearly all parts of the codebase :)

I don't think we need to worry about typing URLs by hand. Only the site's own developers do that ;) But looks do matter.

---

The ID doesn't have to come first. We can imagine e.g. `/123/my-awesome-game` or `/my-awesome-game/123`.

* ID before slug: a [slight advantage](http://stackoverflow.com/questions/27343034/where-to-add-the-id-in-a-url) if the URL gets cut off. StackOverflow does this.
* Slug before ID: The important part for humans (and search engines?) is up front. E.g. The Onion does this, and so does Discourse (which was developed by the StackOverflow crew; Jeff Atwood himself puts in his two cents [here](https://meta.discourse.org/t/url-slugs-where-should-the-topic-id-number-go/1840/11)).

I don't have a strong preference either way. WDYT?

---

For the separator between ID and slug, we don't have to use a slash either:

* `/` gives the cleanest visual separation between the two, but makes it look like one is "subordinate" to the other.
* `-` might make the ID look like part of the slug: `/5-2nd-wejam-event` or `/wejam-event-2-5`.
* `_` gives cleaner separation than `-` but looks a bit odd next to all those hyphens: `/5_2nd-wejam-event`.
* `.` or `,` probably only look good when used at the end: `/2nd-wejam-event.5`, `/2nd-wejam-event,5`.

I think I have a slight preference for `-` over `/` because it's more semantically correct, and also gives us a clean way to distinguish "fixed" parts of the URL like `/event` from "variable" parts like `123-my-event` or `my-event-123`, just by checking whether it starts or ends with a digit. WDYT?

---

Since events are kind of a big thing, and many URLs will be prefixed by them, I agree it might make sense to leave out `/event` (or maybe shorten it, Reddit style, to `/e`). Options:

* `/my-event`: cleanest, but need to be concerned about clashes. Requiring a hyphen would be enough to solve this.
* `/(e|event)/my-event`: second cleanest, no clashes, slug changes will break links.
* `/123-my-event` or `/my-event-123`: less clean, but more consistent, and URL changes are safe.

I'm leaning towards either the first or the third. WDYT?

---

I like putting the entry under the event. It just makes more sense semantically. URL format options are:

* `.../entry/12345-my-entry` or `.../entry/my-entry-12345`: most semantic.
* `.../12345-my-entry` or `.../my-entry-12345`: shorter, but then we can't reuse the same shortcut for, say, an event's blog posts as well; they would have to go under `.../post/my-first-post-45678`.

Again, WDYT?

**Comment by mkalam-alami** [comment]
**IDs positioning**

I'd prefer the "ID before slug" option, for the reason you mentioned but also for copy-pasting comfort. When sharing StackOverflow URLs for instance I know I can just copy the clean http://stackoverflow.com/questions/35529546 rather than the whole http://stackoverflow.com/questions/35529546/should-i-include-my-search-term-in-my-search-path-or-as-a-parameter.

**IDs separator**

I personally find that StackOverflow's `/` makes the URL more readable + makes the above copy/pasting trick more obvious. With a hyphen this *might* lead to confusion, e.g. a game called "Hours to live" will end up with `.../entry/1500-hours-to-live`. Also, "24 Hours to live" would look like `.../entry/1500-24-hours-to-live`.

Using a dot could be an interesting alternative, which I do find acceptable when used at the beginning: `.../entry/1500.hours-to-live`. I still tend to prefer StackOverflow's approach though, if only because the site itself is so widespread that people will immediately "get" how the URLs work just by looking at `.../entry/1500/hours-to-live`.

**IDs in events**

I'd hesitate more between 1 & 2.

With 3, putting entries under events would lead at least to a `/123-event/456-my-game` URL, i.e. having two "ID + slug" combinations which I find removes again from readability.

If you don't have any objections with requiring an hyphen either, 1 sounds good to me. My hesitation was mostly regarding long-time consequences, i.e. what happens if we let users create their own events in the future... But hyphens should be safe enough.

**Entry URLs**

The shorter versions sounds good, I think it makes sense to favor entry URLs over blog posts. This would lead us to:

* Events: `/super-jam-1`
* Entries: `/super-jam-1/1234/awesome-game` or `/super-jam-1/123-awesome-game` 
* Posts: `/post/1234/im-in` or `/post/1234-im-in`

Hmm. By looking at these I actually start to like hyphens as well. More semantic, as you say...

**Comment by ttencate** [comment]
OK, so I'll do `/super-jam-1/1234[-/]awesome-game`. On the hyphen vs. slash, I'll flip a coin when I get to it :)

**Comment by ttencate** [comment]
This is going to work, but there will be room for improvement. In particular, in order to call `buildUrl()` for an entry, the entry must have the related event already loaded, so it can access its slug.

I updated all queries to make this happen, but it is less than ideal. Ideally, `buildUrl()` would fetch the related event, but that would mean it needs to be async. This in turn means async template rendering, which [Nunjucks can do](https://mozilla.github.io/nunjucks/api.html#asynchronous-support) but might be a bit of a hassle.

I also considered denormalizing the database a bit by storing `event_slug` in the `entries` table. This might be a good approach, but again we must be careful to populate this field also on newly created entry objects. And of course when the event's slug is changed, we have to do a big query to update all entries, but that's rare enough to be okay.

Better ideas welcome.

**Comment by mkalam-alami** [comment]
> I also considered denormalizing the database a bit by storing event_slug in the entries table.

That would be my preference actually, I'm already doing that in a couple places.

If we want to make denormalization safe & stupid, we can consider reporting such changes upon `updating` Bookshelf events (if the name is dirty, then update all depending models). It comes with its own risks though so I'm not sure if it's a good idea.

**Comment by ttencate** [comment]
The denormalization approach is much nicer indeed.
